# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftPanel = QtWidgets.QWidget(parent=self.centralwidget)
        self.leftPanel.setObjectName("leftPanel")
        self.leftLayout = QtWidgets.QVBoxLayout(self.leftPanel)
        self.leftLayout.setObjectName("leftLayout")
        self.label_product = QtWidgets.QLabel(parent=self.leftPanel)
        self.label_product.setObjectName("label_product")
        self.leftLayout.addWidget(self.label_product)
        self.productDropdown = QtWidgets.QComboBox(parent=self.leftPanel)
        self.productDropdown.setEditable(True)
        self.productDropdown.setObjectName("productDropdown")
        self.leftLayout.addWidget(self.productDropdown)
        self.label_gin_input = QtWidgets.QLabel(parent=self.leftPanel)
        self.label_gin_input.setObjectName("label_gin_input")
        self.leftLayout.addWidget(self.label_gin_input)
        self.ginInput = QtWidgets.QLineEdit(parent=self.leftPanel)
        self.ginInput.setObjectName("ginInput")
        self.leftLayout.addWidget(self.ginInput)
        self.label_quantity = QtWidgets.QLabel(parent=self.leftPanel)
        self.label_quantity.setObjectName("label_quantity")
        self.leftLayout.addWidget(self.label_quantity)
        self.quantityInput = QtWidgets.QLineEdit(parent=self.leftPanel)
        self.quantityInput.setObjectName("quantityInput")
        self.leftLayout.addWidget(self.quantityInput)
        self.label_gin = QtWidgets.QLabel(parent=self.leftPanel)
        self.label_gin.setObjectName("label_gin")
        self.leftLayout.addWidget(self.label_gin)
        self.ginLabel = QtWidgets.QLabel(parent=self.leftPanel)
        self.ginLabel.setText("")
        self.ginLabel.setObjectName("ginLabel")
        self.leftLayout.addWidget(self.ginLabel)
        self.label_price = QtWidgets.QLabel(parent=self.leftPanel)
        self.label_price.setObjectName("label_price")
        self.leftLayout.addWidget(self.label_price)
        self.priceLabel = QtWidgets.QLabel(parent=self.leftPanel)
        self.priceLabel.setText("")
        self.priceLabel.setObjectName("priceLabel")
        self.leftLayout.addWidget(self.priceLabel)
        self.addButton = QtWidgets.QPushButton(parent=self.leftPanel)
        self.addButton.setObjectName("addButton")
        self.leftLayout.addWidget(self.addButton)
        self.deleteButton = QtWidgets.QPushButton(parent=self.leftPanel)
        self.deleteButton.setObjectName("deleteButton")
        self.leftLayout.addWidget(self.deleteButton)
        self.sendButton = QtWidgets.QPushButton(parent=self.leftPanel)
        self.sendButton.setObjectName("sendButton")
        self.leftLayout.addWidget(self.sendButton)
        self.horizontalLayout.addWidget(self.leftPanel)
        self.rightPanel = QtWidgets.QWidget(parent=self.centralwidget)
        self.rightPanel.setObjectName("rightPanel")
        self.rightLayout = QtWidgets.QVBoxLayout(self.rightPanel)
        self.rightLayout.setObjectName("rightLayout")
        self.label_order = QtWidgets.QLabel(parent=self.rightPanel)
        self.label_order.setObjectName("label_order")
        self.rightLayout.addWidget(self.label_order)
        self.itemsList = QtWidgets.QListWidget(parent=self.rightPanel)
        self.itemsList.setObjectName("itemsList")
        self.rightLayout.addWidget(self.itemsList)
        self.horizontalLayout.addWidget(self.rightPanel)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mlane Delivery"))
        self.label_product.setText(_translate("MainWindow", "Select or Enter the Product Name:"))
        self.label_gin_input.setText(_translate("MainWindow", "Enter Product GIN:"))
        self.ginInput.setPlaceholderText(_translate("MainWindow", "GIN"))
        self.label_quantity.setText(_translate("MainWindow", "Quantity:"))
        self.quantityInput.setPlaceholderText(_translate("MainWindow", "Enter number of items"))
        self.label_gin.setText(_translate("MainWindow", "GIN:"))
        self.label_price.setText(_translate("MainWindow", "Price:"))
        self.addButton.setText(_translate("MainWindow", "Add Item"))
        self.deleteButton.setText(_translate("MainWindow", "Delete Item"))
        self.sendButton.setText(_translate("MainWindow", "Send Order"))
        self.label_order.setText(_translate("MainWindow", "Your order:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
